spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tKTSKXaK1cZDtRKPJn9
      secret-key: YYRXMKCb49JL8Jx63j4ETd3lyKSBXA
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

server:
  port: 30000
